name: opentelemetry
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0
  logging: ^0.11.0
  protobuf: ^1.1.0

dev_dependencies:
  mockito: ^5.0.7
  test: ^1.16.5
  workiva_analysis_options: ^1.2.2
