name: opentelemetry
version: 0.0.0
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.2
  logging: ^0.11.4
  protobuf: ^2.0.0

dev_dependencies:
  mockito: ^5.0.13
  test: ^1.16.5
  workiva_analysis_options: ^1.2.0
