name: opentelemetry_api
version: 0.0.0
publish_to: none

dependencies:
  logging: ^0.11.4
  meta: ^1.2.4
  opentelemetry_context: ^0.0.0

dependency_overrides:
  opentelemetry_context:
    path: ../opentelemetry_context
